lib/cpap/web/router.ex
defmodule CPAP.Web.Router do
  use CPAP.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CPAP.Web.Auth, repo: CPAP.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CPAP.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", CPAP.Web do
    pipe_through [:browser, :authenticate_user]

    resources "/products", ProductController
#    resources "/orders", OrderController
    post "/orders/:id", OrderController, :update
    resources "/orders", OrderController do
      resources "/items", ItemController
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", CPAP do
  #   pipe_through :api
  # end
end

lib/cpap/web/views/layout_view.ex
defmodule CPAP.Web.LayoutView do
  use CPAP.Web, :view
end

lib/cpap/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello CPAP!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">CPAP</a>
          </div>
          <ul class="nav navbar-nav">
            <li><%= link "Home", to: page_path(@conn, :index) %></li>
            <%= if @current_user do %>
              <li><%= link "Products", to: product_path(@conn, :index) %></li>
              <li><%= link "Orders", to: order_path(@conn, :index) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text"><strong class="text-danger"><%= Mix.env |>
            to_string() %></strong></li>
            <li class="navbar-text"><%= @current_user.username %></li>
            <li class="navbar-text"><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
          <li><%= link "Register", to: user_path(@conn, :new) %></li>
          <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          </ul>
        <% end %>
        </div>
      </nav>
      </ol>
        <span class="logo"></span>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-2">
          </div>
          <div class="col-md-7">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
          </div>
          <div class="col-md-3">
          </div>
        </div>
      </div>


    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>