lib/cpap/web/router.ex
defmodule CPAP.Web.Router do
  use CPAP.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CPAP.Web.Auth, repo: CPAP.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CPAP.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", CPAP.Web do
    pipe_through [:browser, :authenticate_user]

    resources "/products", ProductController
#    resources "/orders", OrderController
    post "/orders/:id", OrderController, :update
    resources "/orders", OrderController do
      resources "/items", ItemController
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", CPAP do
  #   pipe_through :api
  # end
end

lib/cpap/web/controllers/order_controller.ex
defmodule CPAP.Web.OrderController do
  use CPAP.Web, :controller

  alias CPAP.Purchases
  alias CPAP.Product

  plug :load_products when action in [:new, :create]

  defp load_products(conn, _) do
    query =
      Product
      |> Product.codes_and_ids(conn.assigns.current_user)

    products = Repo.all query
    assign(conn, :products, products)
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
      [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, user) do
    orders = Purchases.list_orders(user)
    render(conn, "index.html", orders: orders)
  end

  def new(conn, _params, _user) do
    changeset = Purchases.change_order_item(%CPAP.Purchases.Order{items:
    make_4_items()})
    render(conn, "new.html", changeset: changeset)
  end

  defp make_4_items, do: for _ <- 1..4, do: %CPAP.Purchases.Item{}

  def create(conn, %{"order" => order_params}, user) do
    case Purchases.create_order(order_params, user) do
      {:ok, order} ->
        conn
        |> put_flash(:info, "Order created successfully.")
        |> redirect(to: order_path(conn, :show, order))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    order = Purchases.get_order!(id, user)
    #items = Purchases.get_items!(order)
    render(conn, "show.html", order: order)
  end

  def edit(conn, %{"id" => id}, user) do
    order = Purchases.get_order!(id, user)
    #    IO.inspect order, label: "order @ edit"
    # changeset = Purchases.change_order(order)
    changeset = Purchases.change_order_item(order)
    IO.inspect changeset, label: "edit"
    render(conn, "edit.html", order: order, changeset: changeset)
  end

  def update(conn, %{"id" => id, "order" => order_params}, user) do
    order = Purchases.get_order!(id, user)

    case Purchases.update_order(order, order_params) do
      {:ok, order} ->
        conn
        |> put_flash(:info, "Order updated successfully.")
        |> redirect(to: order_path(conn, :show, order))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", order: order, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    order = Purchases.get_order!(id, user)
    {:ok, _order} = Purchases.delete_order(order)

    conn
    |> put_flash(:info, "Order deleted successfully.")
    |> redirect(to: order_path(conn, :index))
  end
end

lib/cpap/web/views/order_view.ex
defmodule CPAP.Web.OrderView do
  use CPAP.Web, :view
end

lib/cpap/web/templates/order/edit.html.eex
<h2>Edit Order</h2>

<%= render "form_items.html", changeset: @changeset,
                        action: order_path(@conn, :update, @order) %>

<span><%= link "Back", to: order_path(@conn, :index) %></span>

lib/cpap/web/templates/order/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :order_date, class: "control-label" %>
    <%= date_select f, :order_date, class: "form-control" %>
    <%= error_tag f, :order_date %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/cpap/web/templates/order/form_items.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :order_date, class: "control-label" %>
    <%= date_select f, :order_date, class: "form-control" %>
    <%= error_tag f, :order_date %>
  </div>

  <%= inputs_for f, :items, fn i -> %>
  <div class="form-group form-inline">
    <%= label i, :qty, "Item ##{i.index + 1}", class: "control-label" %>
    <%= select i, :qty, 0..10, class: "form-control" %>
    <%= label i, :product_id, "#{i.data.product.code}: #{i.data.product.desc}" %>
    <%= "#{i.data.product.code}: #{i.data.product.desc}" %>
    <%= if i.data.id do %>
      <span class="pull-right">
        <%= label i, :delete, "Delete?", class: "control-label" %>
        <%= checkbox i, :delete %>
      </span>
    <% end %>
    <%= if message = i.errors[:qty] do %>
      <span class="help-block"><<%= message %></span>
    <% end %>
  </div>
<% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/cpap/web/templates/order/form_new.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :order_date, class: "control-label" %>
    <%= date_select f, :order_date, year: [options: 2015..2027], default:
    todays_date(), class: "form-control" %>
    <%= error_tag f, :order_date %>
  </div>

  <%= inputs_for f, :items, fn i -> %>
  <div class="form-group">
    <%= label i, :qty, "Item ##{i.index + 1}", class: "control-label" %>
    <%= select i, :qty, 0..10, class: "form-control" %>
    <%= select i, :product_id, @products %>
    <%= if i.data.id do %>
      <span class="pull-right">
        <%= label i, :delete, "Delete?", class: "control-label" %>
        <%= checkbox i, :delete %>
      </span>
    <% end %>
    <%= if message = i.errors[:qty] do %>
      <span class="help-block"><<%= message %></span>
    <% end %>
  </div>
<% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/cpap/web/templates/order/index.html.eex
  <h2>Listing Orders</h2>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Order date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for order <- @orders do %>
    <tr>
      <td><%= link order.order_date, to: order_path(@conn, :show, order) %></td>

      <td class="text-right">
        <span><%= # link "Show", to: order_path(@conn, :show, order), class: "btn btn-default btn-xs" %></span>
        <span><%= # link "Edit", to: order_path(@conn, :edit, order), class: "btn btn-default btn-xs" %></span>
        <span><%= #link "Delete", to: order_path(@conn, :delete, order), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Order", to: order_path(@conn, :new) %></span>

lib/cpap/web/templates/order/new.html.eex
<h2>New Order</h2>

<%= render "form_new.html", changeset: @changeset, products: @products,
                        action: order_path(@conn, :create) %>

<span><%= link "Back", to: order_path(@conn, :index) %></span>

lib/cpap/web/templates/order/show.html.eex
<h2>Show Order</h2>

<table class="table">
  <thead>
    <tr>
      <th>Qty</th>
      <th>Code</th>
      <th>Order date: <%= @order.order_date %></th>
    </tr>
  </thead>
  <tbody>
  <%= for item <- @order.items do %>
    <tr>
      <td><%= item.qty %> </td>
      <td><%= item.product.code %> </td>
      <td><%= item.product.desc %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link "Add item", to: order_item_path(@conn, :new, @order) %>
<br/>
<span><%= link "Edit", to: order_path(@conn, :edit, @order) %></span>
<br/>
<span><%= link "Back", to: order_path(@conn, :index) %></span>
        <span><%= link "Delete", to: order_path(@conn, :delete, @order), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>